import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import '../services/ai_report_service.dart';

const _reportReasons = [
  'Incorrect information',
  'Unsafe or harmful',
  'Offensive or inappropriate',
  'Didn\'t follow my request',
  'Other',
];

class AIReportSection extends StatelessWidget {
  final String feature;
  final String generatedContent;
  final String userPrompt;

  const AIReportSection({
    super.key,
    required this.feature,
    required this.generatedContent,
    required this.userPrompt,
  });

  @override
  Widget build(BuildContext context) {
    final bool isSignedIn = FirebaseAuth.instance.currentUser != null;

    return Card(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
      elevation: 0,
      color: Theme.of(context).cardColor,
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'This content was generated by AI and may contain mistakes.',
              style: TextStyle(fontSize: 14, color: Colors.grey.shade700),
            ),
            const SizedBox(height: 12),
            OutlinedButton.icon(
              onPressed: isSignedIn ? () => _showReportDialog(context) : null,
              icon: const Icon(Icons.flag, size: 18),
              label: const Text('Report AI Response'),
              style: OutlinedButton.styleFrom(
                foregroundColor: Colors.deepPurple,
                side: const BorderSide(color: Colors.deepPurple),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(14),
                ),
              ),
            ),
            if (!isSignedIn) ...[
              const SizedBox(height: 10),
              Text(
                'Sign in to submit AI reports.',
                style: TextStyle(fontSize: 13, color: Colors.grey.shade600),
              ),
            ],
          ],
        ),
      ),
    );
  }

  Future<void> _showReportDialog(BuildContext context) async {
    await showDialog<void>(
      context: context,
      builder: (dialogContext) {
        return _AIReportDialog(
          feature: feature,
          generatedContent: generatedContent,
          userPrompt: userPrompt,
          onSubmitted: () {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text('Thank you. Your report has been submitted.'),
                backgroundColor: Colors.green,
              ),
            );
          },
        );
      },
    );
  }
}

class _AIReportDialog extends StatefulWidget {
  final String feature;
  final String generatedContent;
  final String userPrompt;
  final VoidCallback onSubmitted;

  const _AIReportDialog({
    required this.feature,
    required this.generatedContent,
    required this.userPrompt,
    required this.onSubmitted,
  });

  @override
  State<_AIReportDialog> createState() => _AIReportDialogState();
}

class _AIReportDialogState extends State<_AIReportDialog> {
  String _selectedReason = _reportReasons.first;
  final TextEditingController _commentController = TextEditingController();
  bool _isSubmitting = false;

  @override
  void dispose() {
    _commentController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Report AI Response'),
      content: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            ..._reportReasons.map((reason) {
              return RadioListTile<String>(
                contentPadding: EdgeInsets.zero,
                title: Text(reason),
                value: reason,
                groupValue: _selectedReason,
                onChanged: (value) {
                  if (value == null) return;
                  setState(() {
                    _selectedReason = value;
                  });
                },
              );
            }),
            const SizedBox(height: 12),
            TextField(
              controller: _commentController,
              maxLines: 4,
              decoration: InputDecoration(
                hintText: 'Optional comments',
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
              ),
            ),
          ],
        ),
      ),
      actions: [
        TextButton(
          onPressed: _isSubmitting ? null : () => Navigator.of(context).pop(),
          child: const Text('Cancel'),
        ),
        ElevatedButton(
          onPressed: _isSubmitting ? null : _submit,
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.deepPurple,
            foregroundColor: Colors.white,
          ),
          child: _isSubmitting
              ? const SizedBox(
                  width: 18,
                  height: 18,
                  child: CircularProgressIndicator(
                    color: Colors.white,
                    strokeWidth: 2,
                  ),
                )
              : const Text('Submit'),
        ),
      ],
    );
  }

  Future<void> _submit() async {
    setState(() => _isSubmitting = true);
    try {
      await AIReportService.submitReport(
        feature: widget.feature,
        reason: _selectedReason,
        generatedContent: widget.generatedContent,
        userPrompt: widget.userPrompt,
        comment: _commentController.text.trim().isEmpty
            ? null
            : _commentController.text.trim(),
      );
      if (!mounted) return;
      Navigator.of(context).pop();
      widget.onSubmitted();
    } on FirebaseException catch (e) {
      debugPrint('AI report submission failed: ${e.code} ${e.message}');
      if (!mounted) return;
      setState(() => _isSubmitting = false);
      final message = e.code == 'permission-denied' && FirebaseAuth.instance.currentUser == null
          ? 'Please sign in to submit AI reports.'
          : 'Unable to submit report: ${e.message ?? e.code}';
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(message),
          backgroundColor: Colors.red,
        ),
      );
    } catch (e, stack) {
      debugPrint('AI report submission failed: $e');
      debugPrintStack(stackTrace: stack);
      if (!mounted) return;
      setState(() => _isSubmitting = false);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Unable to submit report: ${e.toString()}'),
          backgroundColor: Colors.red,
        ),
      );
    }
  }
}
